# Base URL
BASE_URL: "https://graph.mapillary.com/images?"

# Paths
BASE_DATA_DIRECTORY: "./data_collection/by_Maz/data/"

LIMIT: 500
MAX_TRIES: 3

# NAIROBI, KENYA BOUNDING BOX (Approximate)
COUNTRY:
    # REGION: 
    #   NAME: "Nairobi"
    #   MIN_LON: 36.75
    #   MIN_LAT: -1.35
    #   MAX_LON: 36.95
    #   MAX_LAT: -1.15
    REGION: 
      NAME: "Mombasa"
      MIN_LON: 39.60
      MIN_LAT: -4.10
      MAX_LON: 39.80
      MAX_LAT: -3.90
    # REGION: 
    #   NAME: "Kisumu"
    #   MIN_LON: 34.65
    #   MIN_LAT: -0.20
    #   MAX_LON: 34.85
    #   MAX_LAT: 0.00
    # REGION: 
    #   NAME: "Eldoret"
    #   MIN_LON: 35.20
    #   MIN_LAT: 0.45
    #   MAX_LON: 35.40
    #   MAX_LAT: 0.65
    # REGION: 
    #   NAME: "Mount Kenya"
    #   MIN_LON: 37.10
    #   MIN_LAT: -0.20
    #   MAX_LON: 37.50
    #   MAX_LAT: 0.20


CSV_HEADERS:
    - "id"
    - "altitude"
    - "atomic_scale"
    - "camera_parameters"
    - "camera_type"
    - "captured_at"
    - "compass_angle"
    - "computed_altitude"
    - "computed_compassangle"
    - "computed_geometry"
    - "computed_rotation"
    - "exif_orientation"
    - "geometry"
    - "height"
    - "is_pano"
    - "make"
    - "model"
    - "thumb_original_url"
    - "merge_cc"
    - "mesh_id"
    - "mesh_url"
    - "sequence"
    - "sfm_cluster_id"
    - "sfm_cluster_url"
    - "width"